/**
 * What is reachable without a Clerk session, as data.
 *
 * Extracted from `middleware.ts` so a test can read it: importing the middleware
 * pulls in Clerk's server SDK, and the invariants worth checking here are facts
 * about two lists rather than about the matcher's runtime.
 *
 * This is the file behind the project's most repeated bug. Everything is private
 * by default, which is the right default and also means that anything meant for
 * a crawler, a webhook or a download is invisible until it is named here — and
 * the failure is a 404 to anonymous requests, which looks like a missing file
 * rather than an access rule. It has bitten `/sitemap.xml`, `/robots.txt`,
 * `/opengraph-image` and `getALPHA-Sync.mq5`.
 */

/** Routes served without a session. An allowlist: absent means protected. */
export const PUBLIC_ROUTES = [
  // The landing page and the waitlist behind it. Everything a visitor can
  // reach before deciding to sign up.
  "/",
  "/api/waitlist",
  // Fired from the public marketing pages only (see VisitTracker). A visitor
  // reading the landing page has no session to protect this behind.
  "/api/track-visit",
  "/login(.*)",
  "/register(.*)",
  // Readable before signing up. A policy you can only see after agreeing to it
  // is not a policy, and the sign-up screen links straight to these.
  "/terms",
  "/privacy",
  "/disclaimer",
  // What shipped, for a visitor deciding whether to trust an active product
  // and a registered user alike — not gated behind a session either way.
  "/changelog",
  // Articles, same reasoning as the changelog — written for whoever is
  // deciding whether to sign up, so gating them behind a session defeats the
  // point.
  "/blog",
  "/blog/(.*)",
  // Feature pages, same reasoning as the blog — written for a visitor
  // deciding whether to sign up, so gating them behind a session defeats
  // the point.
  "/features",
  "/features/(.*)",
  // Generated by Next and fetched by crawlers that have no session. The
  // extension skip-list below does not cover .xml or .txt, so without these a
  // search engine asking for the sitemap gets Clerk's 404 and the site stays
  // invisible.
  "/sitemap.xml",
  "/robots.txt",
  "/opengraph-image",
  // The favicon/app icon, same as `/opengraph-image` above — a browser tab
  // has no Clerk session either.
  "/icon",
  // The manifest's other two icon sizes (192 and the maskable variant) —
  // an installer or launcher reading the manifest has no session either.
  "/icons/192",
  "/icons/512-maskable",
  // Digital Asset Links — Google's crawler checks this to verify the
  // Android TWA package is allowed to open the site full-screen. Google
  // has no Clerk session, same reasoning as the webhooks below.
  "/.well-known/assetlinks.json",
  // Temporary sideload build for testing the Android package before the
  // Play Store listing exists. A phone installing it has no Clerk session
  // either. TODO: remove this route and the file once Play Store testing
  // starts — it doesn't need to stay public.
  "/downloads/getALPHA-test.apk",
  // Stripe has no Clerk session. The webhook authenticates itself with a
  // signature over the raw body instead.
  "/api/billing/webhook",
  // Nor does Vercel's scheduler. That route checks CRON_SECRET itself and
  // refuses everything when the secret is unset.
  "/api/cron/(.*)",
  // Clerk has no session with itself. That route verifies a svix signature
  // over the raw body instead.
  "/api/webhooks/(.*)",
  // A MetaTrader terminal has no browser and no session. That route
  // authenticates with the user's own connection token.
  "/api/mt5/sync",
  // The GA4 first-party proxy (next.config.ts rewrites to googletagmanager.com
  // / google-analytics.com) — an anonymous visitor reading the marketing
  // pages has no session, same as /api/track-visit above. Confirmed
  // 2026-08-19: without this, Clerk's middleware 404s the rewrite before it
  // ever reaches next.config.ts, so GA collected literally nothing. Renamed
  // from "/ga4/..." on 2026-08-26 — see next.config.ts for why.
  "/a3f7e91c2b6d4085/init.js",
  "/a3f7e91c2b6d4085/hit",
] as const;

/**
 * File extensions the middleware does not run for, as regex fragments.
 *
 * Fragments rather than plain strings because two of them need to be: `html?`
 * covers .htm, and `js(?!on)` skips scripts while still protecting .json, which
 * is data and frequently somebody's.
 *
 * `mq5` is here deliberately. It is the MetaTrader program, and it holds no
 * secret — the connection token is pasted in by whoever installs it. Leaving it
 * out meant Clerk protected it and the download answered 404 to anyone not
 * signed in, which is a confusing way to serve a file whose whole purpose is
 * being readable before you trust it.
 */
export const STATIC_EXTENSIONS = [
  "html?",
  "css",
  "js(?!on)",
  "mq5",
  "jpe?g",
  "webp",
  "png",
  "gif",
  "svg",
  "ttf",
  "woff2?",
  "ico",
  "csv",
  "docx?",
  "xlsx?",
  "zip",
  "webmanifest",
] as const;

/**
 * The matcher Next is given, built from the list above.
 *
 * Built rather than written out, so the extensions the middleware skips and the
 * extensions a test can check are the same strings. Two copies of this list is
 * how a file ends up public in the regex and protected in the test, or worse,
 * the other way round.
 */
export const MIDDLEWARE_MATCHER = [
  `/((?!_next|[^?]*\\.(?:${STATIC_EXTENSIONS.join("|")})).*)`,
  // API routes are matched explicitly so they are never skipped.
  "/(api|trpc)(.*)",
];

/** Whether a bare extension — "mq5", "json" — is one the middleware skips. */
export function isStaticExtension(extension: string): boolean {
  return new RegExp(`^(?:${STATIC_EXTENSIONS.join("|")})$`).test(extension);
}
