import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import test from "node:test";
import {
  MIDDLEWARE_MATCHER,
  PUBLIC_ROUTES,
  STATIC_EXTENSIONS,
  isStaticExtension,
} from "../src/lib/public-routes.ts";

/**
 * The project's most repeated bug, as a test.
 *
 * Everything is private by default, which is the right default and also means
 * anything meant for a crawler, a webhook or a download is invisible until it is
 * named — and the symptom is a 404 to anonymous requests, which reads like a
 * missing file rather than an access rule. It has cost hours four times:
 * `/sitemap.xml`, `/robots.txt`, `/opengraph-image`, `getALPHA-Sync.mq5`.
 *
 * No server and no browser: the invariants are facts about two lists, so they
 * are checkable in a millisecond and run on every push.
 */

const publicFiles = readdirSync("public", { withFileTypes: true })
  .filter((entry) => entry.isFile())
  .map((entry) => entry.name);

test("every file served from public/ has an extension the middleware skips", () => {
  // The self-maintaining half. Drop a .pdf in public/ and this fails before
  // anybody discovers the download 404s for signed-out visitors.
  const protectedFiles = publicFiles.filter((name) => {
    const dot = name.lastIndexOf(".");
    if (dot === -1) return true;
    return !isStaticExtension(name.slice(dot + 1).toLowerCase());
  });

  assert.deepEqual(
    protectedFiles,
    [],
    `these files in public/ would answer 404 to anonymous requests — add the extension to STATIC_EXTENSIONS or the path to PUBLIC_ROUTES: ${protectedFiles.join(", ")}`,
  );
});

test("public/ is actually being read, so the check above cannot pass vacuously", () => {
  // A test that silently examines an empty list is worse than no test.
  assert.ok(publicFiles.length > 0);
  assert.ok(publicFiles.includes("getALPHA-Sync.mq5"));
  assert.ok(publicFiles.includes("getALPHA-Sync.mq4"));
});

test("the MetaTrader downloads are reachable without signing in", () => {
  // They hold no secret — the connection token is pasted in by whoever
  // installs one — and their whole purpose is being readable before you
  // trust them.
  assert.equal(isStaticExtension("mq5"), true);
  assert.equal(isStaticExtension("mq4"), true);
});

test("the crawler-facing routes are on the allowlist", () => {
  // These are generated by Next rather than files in public/, so the extension
  // skip-list cannot cover them. .xml and .txt are deliberately not skipped.
  for (const route of ["/sitemap.xml", "/robots.txt", "/opengraph-image"]) {
    assert.ok(
      PUBLIC_ROUTES.includes(route as (typeof PUBLIC_ROUTES)[number]),
      `${route} is protected, so crawlers get a 404`,
    );
  }
});

test("the callers that have no session are on the allowlist", () => {
  // Each authenticates itself: a Stripe signature, a svix signature, the cron
  // secret, the terminal's own token.
  for (const route of [
    "/api/billing/webhook",
    "/api/webhooks/(.*)",
    "/api/cron/(.*)",
    "/api/mt5/sync",
    "/api/mt4/sync",
  ]) {
    assert.ok(PUBLIC_ROUTES.includes(route as (typeof PUBLIC_ROUTES)[number]));
  }
});

test("json stays protected while js does not", () => {
  // `js(?!on)` is the reason that lookahead exists: scripts are static, and
  // .json is data that is frequently somebody's.
  assert.equal(isStaticExtension("js"), true);
  assert.equal(isStaticExtension("json"), false);
});

test("nothing private has crept onto the allowlist", () => {
  // The check that matters most and cannot be automated away: an allowlist is
  // only as good as the review of what is on it.
  const mustStayPrivate = [
    "/dashboard",
    "/dashboard/(.*)",
    "/api/trades",
    "/api/trades/(.*)",
    "/api/ai/coach",
    "/api/ai/session-brief",
    "/api/mt5/connection",
    "/api/mt4/connection",
    "/api/billing/checkout",
    "/api/support",
    "/api/watchlist",
  ];

  for (const route of mustStayPrivate) {
    assert.ok(
      !PUBLIC_ROUTES.includes(route as (typeof PUBLIC_ROUTES)[number]),
      `${route} is on the public allowlist and must not be`,
    );
  }
});

test("api routes are matched explicitly so they are never skipped", () => {
  // Without this line an /api path ending in a static-looking extension would
  // bypass the middleware entirely.
  assert.ok(MIDDLEWARE_MATCHER.includes("/(api|trpc)(.*)"));
});

test("the matcher still compiles as a regex", () => {
  // It is handed to Next as a string. A typo here takes every route down.
  assert.doesNotThrow(() => new RegExp(MIDDLEWARE_MATCHER[0]));
});

/**
 * The literal in `middleware.ts` has to match what the shared list generates.
 *
 * The matcher cannot simply import `MIDDLEWARE_MATCHER`: Next parses that config
 * object at compile time and rejects anything it cannot read statically — the
 * build fails outright with "needs to have a very specific format". So the
 * pattern is written out in both places, and this is what stops the two copies
 * diverging.
 *
 * Compared as source text on purpose. The point is that the file *contains a
 * literal*, and reading it any other way would test something else.
 */
test("the literal matcher in middleware.ts matches the generated one", () => {
  const source = readFileSync("src/middleware.ts", "utf8");

  for (const pattern of MIDDLEWARE_MATCHER) {
    // JSON.stringify produces exactly the escaping the source needs, which is
    // where a hand-edit goes wrong: `"\."` in a JS string is a plain dot and
    // matches any character, quietly widening what the middleware skips.
    assert.ok(
      source.includes(JSON.stringify(pattern)),
      `middleware.ts does not contain ${JSON.stringify(pattern)} — the literal and public-routes.ts have diverged`,
    );
  }
});

test("the extension list reaches the literal, every fragment of it", () => {
  const source = readFileSync("src/middleware.ts", "utf8");

  for (const fragment of STATIC_EXTENSIONS) {
    assert.ok(
      source.includes(fragment),
      `${fragment} is in STATIC_EXTENSIONS but not in the middleware literal`,
    );
  }
});
