import type { Metadata } from "next";
import LegalDocument, { Clause } from "@/components/LegalDocument";
import { LEGAL_VERSIONS, OPERATOR } from "@/lib/legal/documents";

export const metadata: Metadata = {
  title: "Risk Disclaimer · getALPHA",
  description:
    "getALPHA is an educational and informational tool. It does not provide financial advice or trading signals.",
  alternates: { canonical: "/disclaimer" },
};

export default function DisclaimerPage() {
  return (
    <LegalDocument
      title="Risk Disclaimer"
      version={LEGAL_VERSIONS.disclaimer}
      summary="Read this before using anything on this platform. It sets out what getALPHA is, what it is not, and who carries the risk of decisions made using it."
    >
      <Clause heading="1. What this platform is">
        <p>
          getALPHA is an <strong>educational and informational tool</strong>. It
          organises publicly available market data — an economic calendar, price
          history, news headlines — and produces written summaries and reviews of
          a user&rsquo;s own recorded trading.
        </p>
        <p>
          Nothing on this platform is produced with knowledge of any
          individual&rsquo;s financial circumstances, objectives, tax position,
          risk tolerance or investment experience.
        </p>
      </Clause>

      <Clause heading="2. What this platform is not">
        <p>
          {OPERATOR.legalName} is <strong>not</strong> an investment firm,
          investment adviser, financial adviser, broker, dealer, portfolio
          manager, or a provider of any regulated investment service. It is not
          authorised or supervised by any financial regulator.
        </p>
        <p>
          No content on this platform constitutes{" "}
          <strong>
            investment advice, financial advice, a personal recommendation, a
            trading signal, an inducement to trade, an offer, or a solicitation
          </strong>{" "}
          to buy or sell any financial instrument.
        </p>
        <p>
          The written summaries, session briefs, reviews and scores produced here
          are commentary on data the user supplied or that was collected from
          public sources. They are not a recommendation to enter, exit, hold or
          size any position, and they must not be relied on as one.
        </p>
      </Clause>

      <Clause heading="3. You carry the risk">
        <p>
          <strong>
            You alone are responsible for every financial decision you make.
          </strong>{" "}
          Any decision to trade, and the consequences of that decision, are
          yours. If you act on anything you read here, you do so entirely at your
          own risk.
        </p>
        <p>
          Trading leveraged instruments — including foreign exchange, contracts
          for difference, commodities and cryptoassets — carries a high risk of
          loss. It is possible to lose more than the amount originally deposited.
          These products are not suitable for everyone.
        </p>
        <p>
          Past performance is not a reliable indicator of future results. No
          result shown, described or implied on this platform should be taken as
          a promise, projection or guarantee of any outcome.
        </p>
        <p>
          Seek independent advice from a licensed professional in your own
          jurisdiction before making any financial decision.
        </p>
      </Clause>

      <Clause heading="4. Automated and AI-generated content">
        <p>
          Parts of this platform are generated by an automated language model.
          Such output can be incomplete, out of date, or wrong, and can be wrong
          while appearing confident and specific.
        </p>
        <p>
          It is not reviewed by a human before you see it, and it is not checked
          for suitability for you. Treat it as a starting point for your own
          analysis, never as a conclusion, and never as a reason to place a
          trade.
        </p>
      </Clause>

      <Clause heading="5. Market data">
        <p>
          Market data, calendar entries and news headlines are obtained from
          third-party sources. They may be delayed, incomplete, interrupted or
          inaccurate, and the platform indicates when it is showing stored data
          rather than live data.
        </p>
        <p>
          {OPERATOR.legalName} does not warrant the accuracy, completeness,
          timeliness or continued availability of any data shown, and accepts no
          liability for decisions taken on the basis of it.
        </p>
      </Clause>

      <Clause heading="6. No liability for trading losses">
        <p>
          To the fullest extent permitted by applicable law,{" "}
          {OPERATOR.legalName} and its officers, employees and suppliers accept
          no liability for any loss or damage — including trading losses, loss of
          profit, loss of opportunity, loss of data, or indirect or consequential
          loss — arising out of or in connection with the use of, or reliance on,
          this platform or any content produced by it.
        </p>
        <p>
          Nothing in this disclaimer excludes or limits liability where such
          exclusion or limitation is not permitted by law.
        </p>
      </Clause>

      <Clause heading="7. Your jurisdiction is your responsibility">
        <p>
          This platform is operated from {OPERATOR.jurisdiction}. It is not
          directed at any person in any jurisdiction where making it available
          would be contrary to local law or regulation.
        </p>
        <p>
          You are responsible for determining whether your use of this platform
          is lawful where you are, and for complying with any local rules that
          apply to you.
        </p>
      </Clause>

      <Clause heading="8. Contact">
        <p>
          {OPERATOR.legalName}, {OPERATOR.address}. Questions about this
          disclaimer: {OPERATOR.contactEmail}.
        </p>
      </Clause>
    </LegalDocument>
  );
}
