import type { Metadata } from "next";
import Link from "next/link";
import BlogPost from "@/components/BlogPost";

export const metadata: Metadata = {
  title: {
    absolute:
      "Averaging Down: When Adding to a Loser Makes Sense, and When It Doesn't · getALPHA",
  },
  description:
    "Adding to a losing position is either a planned scale-in with a defined cap, or a way to avoid admitting the first entry was wrong. The trade history looks identical either way — until the risk numbers are pulled apart.",
  alternates: { canonical: "/blog/averaging-down" },
};

export default function Page() {
  return (
    <BlogPost
      title="Averaging Down: When Adding to a Loser Makes Sense, and When It Doesn't"
      date="2026-09-08"
    >
      <p>
        The position is down, and adding to it lowers the average entry price — which means the
        market has to move less to get back to breakeven. That single fact makes averaging down
        feel like a mathematical improvement almost every time it&apos;s considered. It can be
        one. It can also be the exact moment a defined, sized loss turns into an undefined one.
        The trade log records both cases the same way: an entry, then a bigger entry at a worse
        price. Only the plan behind them tells the two apart.
      </p>

      <h2>Two things that look identical and aren&apos;t</h2>
      <p>
        A scale-in is a position built in planned pieces, each one sized in advance, with a total
        risk cap decided before the first order went in. The second and third entries were always
        going to happen at those levels if the market got there — they&apos;re not a reaction to
        the trade going wrong, they&apos;re the plan playing out.
      </p>
      <p>
        Averaging down as a rescue is different in every way that matters and identical in every
        way a spreadsheet can see: the position is down, more size gets added at a worse price, and
        the stated reason is usually some version of &ldquo;it&apos;s a better price now than it
        was.&rdquo; The stop from the original entry is gone by this point too, in almost every
        version of this trade — a stop set at the first entry&apos;s risk tolerance doesn&apos;t
        survive a second entry that doubles the size without being widened along with it.
      </p>

      <h2>What it does to the risk that was actually taken</h2>
      <p>
        The first entry was sized against a specific stop distance, at whatever risk percentage the
        plan called for. Adding size at a worse price without a new stop plan doesn&apos;t just add
        risk on top of that — it changes what the original risk number even means, because the
        average entry has moved but the account&apos;s actual exposure to further downside has
        grown, not shrunk. A 1% risk trade that gets averaged down twice is very often a 2.5–3%
        risk trade wearing the label of the position it started as, with nobody having decided at
        any point that 3% was the number for this setup.
      </p>
      <p>
        This is the part that doesn&apos;t show up until it&apos;s pulled out of the trade history
        deliberately: not the size of any single loss, but the gap between the risk that was
        decided on at entry and the risk that was actually sitting in the account by the time the
        position closed.
      </p>

      <h2>When it holds up</h2>
      <ul>
        <li>
          <strong>The added size was decided before the first entry</strong>, not invented after
          seeing the position underwater — a scale-in plan with defined levels and a stated total
          size, not a reaction.
        </li>
        <li>
          <strong>There&apos;s a hard cap on total risk</strong>, set before any entry went in, that
          the combined position can&apos;t exceed regardless of how many levels get filled.
        </li>
        <li>
          <strong>The stop moves with the plan, not with the loss</strong> — the invalidation level
          for the full position was defined up front, not pushed further away each time price gets
          closer to it.
        </li>
        <li>
          <strong>The thesis hasn&apos;t changed</strong> — the reason for being in the trade at the
          second entry is the same reason as at the first, not a new story constructed to justify
          staying in.
        </li>
      </ul>

      <h2>When it doesn&apos;t</h2>
      <p>
        Almost everything else. The version worth watching for is the one that starts with
        &ldquo;the setup is even better now&rdquo; after the position has already moved against
        it — because that reasoning is available on every single losing trade, at every price,
        without exception. It isn&apos;t analysis of the market. It&apos;s a justification
        generated by not wanting the first entry to have been wrong, and it will produce exactly as
        much conviction on the trade that keeps going against you as on the one that turns around.
        The tell is usually simple: if the size and the level of the second entry weren&apos;t
        written down before the first entry was placed, the second entry isn&apos;t part of a plan.
      </p>

      <h2>What to track</h2>
      <ul>
        <li>
          <strong>Total position risk vs. planned risk</strong> — the actual account exposure once
          every add is included, measured against what was decided before the first entry.
        </li>
        <li>
          <strong>Whether the stop was defined before or after the add</strong> — a stop set at the
          time of the first entry and never revisited is a different trade than one recalculated
          after the position went underwater.
        </li>
        <li>
          <strong>Win rate and expectancy on averaged trades, kept separate</strong> from
          single-entry trades — a strategy&apos;s real numbers can look very different once these
          two are no longer blended into one line.
        </li>
        <li>
          <strong>How often an add was planned in advance</strong> versus decided in the moment,
          since that ratio is usually the honest answer to whether this is a technique or a habit.
        </li>
      </ul>
      <p>
        None of this needs to be judged trade by trade in real time. It needs a record that keeps
        every entry into a position as its own line, with its own size and its own price, instead
        of collapsing them into a single average that hides how the position actually got built.
      </p>

      <h2>Why this is easy to lose in a manual log</h2>
      <p>
        A spreadsheet filled in once the position closes usually has room for one entry price, one
        exit price and one size — the sequence of adds that produced that average, and the risk
        decided at each one, is exactly the detail that doesn&apos;t survive being summarized after
        the fact. <Link href="/features/trading-journal">getALPHA</Link> pulls every fill from MT5
        as its own line as trades close, so a position built from three entries stays visible as
        three entries. That&apos;s the record{" "}
        <Link href="/features/ai-trade-coach">getALPHA&apos;s AI coach</Link> needs to tell a sized
        scale-in from an averaged-down rescue — the two trades that look the same from the outside,
        and aren&apos;t.
      </p>
    </BlogPost>
  );
}
