import { clerkMiddleware, createRouteMatcher } from "@clerk/nextjs/server";
import { NextResponse } from "next/server";
import {
  REFERRAL_CODE_PATTERN,
  REFERRAL_COOKIE,
  REFERRAL_COOKIE_MAX_AGE,
} from "@/lib/referral/cookie";

/**
 * Next 16 deprecates this file convention in favour of `proxy.ts`, and the
 * build prints a warning about it. Renaming the file took the whole site down
 * with MIDDLEWARE_INVOCATION_FAILED on Vercel — Clerk exports no `clerkProxy`
 * counterpart and `clerkMiddleware` did not survive the move. The warning
 * stays until Clerk supports the new convention.
 *
 * Everything is private by default. Only the sign-in and sign-up screens are
 * reachable without a session — an allowlist, so a route added later is
 * protected unless someone deliberately opens it.
 */
const isPublicRoute = createRouteMatcher([
  // The landing page and the waitlist behind it. Everything a visitor can
  // reach before deciding to sign up.
  "/",
  "/api/waitlist",
  "/login(.*)",
  "/register(.*)",
  // Readable before signing up. A policy you can only see after agreeing to it
  // is not a policy, and the sign-up screen links straight to these.
  "/terms",
  "/privacy",
  "/disclaimer",
  // Generated by Next, and fetched by crawlers that have no session. The
  // matcher below only skips static file extensions, and .xml and .txt are not
  // among them — so without these three, a search engine asking for the
  // sitemap got Clerk's 404 and the site stayed invisible.
  "/sitemap.xml",
  "/robots.txt",
  "/opengraph-image",
  // Stripe has no Clerk session. The webhook authenticates itself with a
  // signature over the raw body instead.
  "/api/billing/webhook",
  // Nor does Vercel's scheduler. That route checks CRON_SECRET itself and
  // refuses everything when the secret is unset.
  "/api/cron/(.*)",
  // Clerk has no session with itself. That route verifies a svix signature
  // over the raw body instead.
  "/api/webhooks/(.*)",
  // A MetaTrader terminal has no browser and no session. That route
  // authenticates with the user's own connection token.
  "/api/mt5/sync",
]);

export default clerkMiddleware(async (auth, request) => {
  if (!isPublicRoute(request)) {
    await auth.protect();
  }

  const response = NextResponse.next();

  // An invite code arrives on the landing page but is only usable after the
  // visitor has signed up, which happens on Clerk's pages. The cookie is what
  // carries it across that gap. Set here rather than on the page so it survives
  // whichever route the link points at.
  const ref = request.nextUrl.searchParams.get("ref")?.toUpperCase();

  if (
    ref &&
    REFERRAL_CODE_PATTERN.test(ref) &&
    !request.cookies.has(REFERRAL_COOKIE)
  ) {
    // Not `httpOnly: false` — nothing in the browser needs to read it, and
    // `lax` is enough for a code that only ever arrives by following a link.
    response.cookies.set(REFERRAL_COOKIE, ref, {
      maxAge: REFERRAL_COOKIE_MAX_AGE,
      httpOnly: true,
      sameSite: "lax",
      secure: process.env.NODE_ENV === "production",
      path: "/",
    });
  }

  return response;
});

export const config = {
  matcher: [
    // Everything except Next internals and static files.
    //
    // `mq5` is in the list deliberately. It is the MetaTrader program, and it
    // holds no secret — the connection token is pasted in by whoever installs
    // it. Leaving it out meant Clerk protected it and the download answered 404
    // to anyone not signed in, which is a confusing way to serve a file whose
    // whole purpose is being readable before you trust it.
    "/((?!_next|[^?]*\\.(?:html?|css|js(?!on)|mq5|jpe?g|webp|png|gif|svg|ttf|woff2?|ico|csv|docx?|xlsx?|zip|webmanifest)).*)",
    // API routes are matched explicitly so they are never skipped.
    "/(api|trpc)(.*)",
  ],
};
